# Generated by Django 5.2.15 on 2026-06-21 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertePrioritaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('severite', models.CharField(choices=[('Élevée', 'Élevée'), ('Moyenne', 'Moyenne'), ('Faible', 'Faible')], max_length=10)),
                ('commune', models.CharField(blank=True, max_length=50)),
                ('est_traitee', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerte prioritaire',
                'verbose_name_plural': 'Alertes prioritaires',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DossierFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=50)),
                ('fiscalite_estimee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_reclame', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier fiscal',
                'verbose_name_plural': 'Dossiers fiscaux',
                'ordering': ['-montant_reclame'],
            },
        ),
        migrations.CreateModel(
            name='DonneeCollectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=50)),
                ('Marque', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, default='Abidjan', max_length=50)),
                ('commune', models.CharField(blank=True, default='Abidjan', max_length=50)),
                ('region', models.CharField(blank=True, default='Abidjan', max_length=50)),
                ('district', models.CharField(blank=True, default='Abidjan', max_length=50)),
                ('village', models.CharField(blank=True, default='Abidjan', max_length=50)),
                ('quartier', models.CharField(blank=True, max_length=50)),
                ('nomsite', models.CharField(blank=True, default='RAS', max_length=50)),
                ('type_support', models.CharField(blank=True, max_length=50)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('nombre_support', models.FloatField(blank=True, null=True)),
                ('nombre_face', models.FloatField(blank=True, null=True)),
                ('surfaceODP', models.FloatField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=50)),
                ('etat_support', models.CharField(blank=True, choices=[('Bon', 'Bon'), ('Défraichi', 'Défraichi'), ('Détérioré', 'Détérioré')], max_length=50)),
                ('typesite', models.CharField(blank=True, max_length=50)),
                ('visibilite', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('observation', models.CharField(blank=True, max_length=50)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('image_support', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('image_support_s', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('signature1', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('Rnom', models.CharField(blank=True, max_length=50)),
                ('Rprenom', models.CharField(blank=True, max_length=50)),
                ('Rcontact', models.CharField(blank=True, max_length=50)),
                ('Snom', models.CharField(blank=True, max_length=50)),
                ('Sprenom', models.CharField(blank=True, max_length=50)),
                ('Scontact', models.CharField(blank=True, max_length=50)),
                ('duree', models.FloatField(blank=True, null=True)),
                ('anciennete', models.BooleanField(blank=True, default=False)),
                ('TSP', models.FloatField(blank=True, null=True)),
                ('ODP', models.BooleanField(blank=True, default=False)),
                ('AP', models.BooleanField(blank=True, default=False)),
                ('APA', models.BooleanField(blank=True, default=False)),
                ('APT', models.BooleanField(blank=True, default=False)),
                ('AE', models.BooleanField(blank=True, default=False)),
                ('AEA', models.BooleanField(blank=True, default=False)),
                ('AET', models.BooleanField(blank=True, default=False)),
                ('tauxCommune', models.BooleanField(blank=True, default=False)),
                ('tauxRegion', models.BooleanField(blank=True, default=False)),
                ('tauxDistrict', models.BooleanField(blank=True, default=False)),
                ('ODP_value', models.FloatField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support publicitaire',
                'verbose_name_plural': 'Supports publicitaires',
                'ordering': ['-date_collecte'],
            },
        ),
        migrations.CreateModel(
            name='Negociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(max_length=50)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_recalcule', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_negocie', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('type_prochaine_action', models.CharField(blank=True, choices=[('reunion', 'Réunion'), ('argumentaire', "Envoi d'argumentaire"), ('relance', 'Relance')], max_length=20)),
                ('date_prochaine_action', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('agent_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Négociation',
                'verbose_name_plural': 'Négociations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ArgumentairePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('absent', 'Supports absents'), ('doublon', 'Doublons'), ('periode', 'Mauvaise période'), ('surface', 'Mauvaise surface')], max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('negociation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argumentaires', to='core.negociation')),
            ],
            options={
                'verbose_name': 'Argumentaire prêt',
                'verbose_name_plural': 'Argumentaires prêts',
            },
        ),
    ]
