# Generated by Django 5.2.15 on 2026-06-21 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteprioritaire',
            name='entreprise_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='entreprise_rel',
            field=models.ForeignKey(blank=True, help_text="Entreprise propriétaire (isolation multi-tenant). Le champ 'entreprise' texte ci-dessous reste conservé pour compatibilité avec l'app mobile.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='dossierfiscal',
            name='entreprise_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_fiscaux', to='accounts.entreprise'),
        ),
        migrations.AddField(
            model_name='negociation',
            name='entreprise_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negociations', to='accounts.entreprise'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type_activite', models.CharField(choices=[('success', 'Succès'), ('info', 'Information'), ('warning', 'Avertissement')], default='info', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='accounts.entreprise')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-cree_le'],
            },
        ),
    ]
