# Generated by Django 5.2.15 on 2026-06-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_alerteprioritaire_entreprise_rel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('campagne', models.CharField(blank=True, max_length=100)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé')], default='brouillon', max_length=20)),
                ('commune', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('type_support', models.CharField(blank=True, max_length=50)),
                ('canal', models.CharField(blank=True, max_length=50)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(default=12)),
                ('quantite', models.IntegerField(default=1)),
                ('taux_tsp', models.FloatField(default=5.0, help_text='Taux TSP en %')),
                ('odp_applicable', models.BooleanField(default=False)),
                ('taxes_communales', models.BooleanField(default=True)),
                ('cout_tsp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_odp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('risque_fiscal', models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='accounts.entreprise')),
            ],
            options={
                'verbose_name': 'Simulation fiscale',
                'verbose_name_plural': 'Simulations fiscales',
                'ordering': ['-cree_le'],
            },
        ),
    ]
