# Generated by Django 5.2.15 on 2026-06-24 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_simulationfiscale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreDeRecettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_collectivite', models.CharField(choices=[('commune', 'Commune'), ('region', 'Région'), ('district', 'District')], default='commune', max_length=20)),
                ('nom_collectivite', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('interlocuteur', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='ordres_recettes/')),
                ('montant_reclame', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalites', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_annexes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nombre_supports_factures', models.IntegerField(default=0)),
                ('type_support_facture', models.CharField(blank=True, max_length=50)),
                ('surface_facturee', models.FloatField(blank=True, null=True)),
                ('localite_facturee', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('en_analyse', 'En analyse'), ('conteste', 'Contesté'), ('valide', 'Validé'), ('negocie', 'Négocié'), ('paye', 'Payé')], default='recu', max_length=20)),
                ('prochaine_action', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entreprise_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_recettes', to='accounts.entreprise')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_recettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre de recettes',
                'verbose_name_plural': 'Ordres de recettes',
                'ordering': ['-cree_le'],
            },
        ),
    ]
