# Generated by Django 5.2.15 on 2026-07-19 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_canal_commune_district_etat_marque_quartier_region_and_more'),
        ('core', '0004_ordrederecettes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donneecollectee',
            name='pdv_reference',
            field=models.SlugField(blank=True, help_text="Identifiant du PDV, partagé par tous les supports d'un même point de vente. Auto-généré à la création si absent (nouveau PDV), ou fourni par le client mobile quand l'agent rattache un support à un PDV existant (revisite).", max_length=80),
        ),
        migrations.AddIndex(
            model_name='donneecollectee',
            index=models.Index(fields=['pdv_reference'], name='core_donnee_pdv_ref_2d269a_idx'),
        ),
    ]
