# Generated by Django 5.2.15 on 2026-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='entreprises/logos/'),
        ),
    ]
