# Generated by Django 5.2.15 on 2026-06-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entreprise_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_odp', models.DecimalField(blank=True, decimal_places=2, help_text='Occupation du Domaine Public', max_digits=6, null=True, verbose_name='Taux ODP (%)')),
                ('taux_tsp', models.DecimalField(blank=True, decimal_places=2, help_text='Taxe sur Support Publicitaire', max_digits=6, null=True, verbose_name='Taux TSP (%)')),
                ('taux_ap', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire', max_digits=6, null=True, verbose_name='Taux AP (%)')),
                ('taux_apa', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Animé', max_digits=6, null=True, verbose_name='Taux APA (%)')),
                ('taux_apt', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Temporaire', max_digits=6, null=True, verbose_name='Taux APT (%)')),
                ('taux_ae', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique', max_digits=6, null=True, verbose_name='Taux AE (%)')),
                ('taux_aea', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Animé', max_digits=6, null=True, verbose_name='Taux AEA (%)')),
                ('taux_aet', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Temporaire', max_digits=6, null=True, verbose_name='Taux AET (%)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la commune')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['region__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_odp', models.DecimalField(blank=True, decimal_places=2, help_text='Occupation du Domaine Public', max_digits=6, null=True, verbose_name='Taux ODP (%)')),
                ('taux_tsp', models.DecimalField(blank=True, decimal_places=2, help_text='Taxe sur Support Publicitaire', max_digits=6, null=True, verbose_name='Taux TSP (%)')),
                ('taux_ap', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire', max_digits=6, null=True, verbose_name='Taux AP (%)')),
                ('taux_apa', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Animé', max_digits=6, null=True, verbose_name='Taux APA (%)')),
                ('taux_apt', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Temporaire', max_digits=6, null=True, verbose_name='Taux APT (%)')),
                ('taux_ae', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique', max_digits=6, null=True, verbose_name='Taux AE (%)')),
                ('taux_aea', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Animé', max_digits=6, null=True, verbose_name='Taux AEA (%)')),
                ('taux_aet', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Temporaire', max_digits=6, null=True, verbose_name='Taux AET (%)')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du district')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du quartier')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
                'ordering': ['commune__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_odp', models.DecimalField(blank=True, decimal_places=2, help_text='Occupation du Domaine Public', max_digits=6, null=True, verbose_name='Taux ODP (%)')),
                ('taux_tsp', models.DecimalField(blank=True, decimal_places=2, help_text='Taxe sur Support Publicitaire', max_digits=6, null=True, verbose_name='Taux TSP (%)')),
                ('taux_ap', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire', max_digits=6, null=True, verbose_name='Taux AP (%)')),
                ('taux_apa', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Animé', max_digits=6, null=True, verbose_name='Taux APA (%)')),
                ('taux_apt', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Publicitaire Temporaire', max_digits=6, null=True, verbose_name='Taux APT (%)')),
                ('taux_ae', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique', max_digits=6, null=True, verbose_name='Taux AE (%)')),
                ('taux_aea', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Animé', max_digits=6, null=True, verbose_name='Taux AEA (%)')),
                ('taux_aet', models.DecimalField(blank=True, decimal_places=2, help_text='Affichage Électronique Temporaire', max_digits=6, null=True, verbose_name='Taux AET (%)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la région')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['district__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportPublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=50)),
                ('type_support', models.CharField(max_length=50)),
                ('nombre_face', models.FloatField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support publicitaire',
                'verbose_name_plural': 'Supports publicitaires',
            },
        ),
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTAP', models.CharField(max_length=50)),
                ('TTPAT', models.CharField(max_length=50)),
                ('TAE', models.CharField(max_length=50)),
                ('TAEAT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilite', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['quartier__nom', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='affectationagent',
            options={'ordering': ['agent__nom'], 'verbose_name': 'Affectation agent', 'verbose_name_plural': 'Affectations agents'},
        ),
        migrations.RemoveConstraint(
            model_name='affectationagent',
            name='unique_affectation_par_agent',
        ),
        migrations.RemoveField(
            model_name='affectationagent',
            name='type_zone',
        ),
        migrations.RemoveField(
            model_name='affectationagent',
            name='valeur_zone',
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='accounts.commune'),
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='quartier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartiers', to='accounts.commune'),
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='accounts.quartier'),
        ),
        migrations.AddField(
            model_name='region',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='accounts.district'),
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='accounts.region'),
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='accounts.region'),
        ),
        migrations.AddField(
            model_name='zone',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='accounts.quartier'),
        ),
        migrations.AddField(
            model_name='affectationagent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='accounts.zone'),
        ),
        migrations.AddConstraint(
            model_name='quartier',
            constraint=models.UniqueConstraint(fields=('commune', 'nom'), name='unique_quartier_par_commune'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('district', 'nom'), name='unique_region_par_district'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('region', 'nom'), name='unique_commune_par_region'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('quartier', 'nom'), name='unique_zone_par_quartier'),
        ),
    ]
